targets:
  $default:
    sources:
      - lib/**
      - graphql_queries/**
      - graphql_schema/schema.graphql
    builders:
      artemis:
        options:
          generate_helpers: true
          scalar_mapping:
            - graphql_type: BigInteger
              dart_type: int
              use_custom_parser: true
          schema_mapping:

            ##### Mutation ####
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/mutation/login_mutation.graphql
              output: lib/data/graphql/mutation/login_mutation_graphql.dart
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/mutation/login_with_auth_mutation.graphql
              output: lib/data/graphql/mutation/login_with_auth_mutation_graphql.dart
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/mutation/register_otp_mutation.graphql
              output: lib/data/graphql/mutation/register_otp_mutation_graphql.dart
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/mutation/update_password_mutation.graphql
              output: lib/data/graphql/mutation/update_password_mutation_graphql.dart
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/mutation/update_profile_mutation.graphql
              output: lib/data/graphql/mutation/update_profile_mutation_graphql.dart
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/mutation/verify_otp_mutation.graphql
              output: lib/data/graphql/mutation/verify_otp_mutation_graphql.dart

            #### Query ####
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/query/app_notification_item_query.graphql
              output: lib/data/graphql/query/app_notification_item_query_graphql.dart
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/query/app_notification_list_query.graphql
              output: lib/data/graphql/query/app_notification_list_query_graphql.dart
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/query/feature_flag_clear_feature_cache_query.graphql
              output: lib/data/graphql/query/feature_flag_clear_feature_cache_query_graphql.dart
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/query/feature_flag_clear_version_cache_query.graphql
              output: lib/data/graphql/query/feature_flag_clear_version_cache_query_graphql.dart
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/query/feature_flag_get_user_version_query.graphql
              output: lib/data/graphql/query/feature_flag_get_user_version_query_graphql.dart
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/query/feature_flag_list_feature_query.graphql
              output: lib/data/graphql/query/feature_flag_list_feature_query_graphql.dart
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/query/payment_get_bank_list_query.graphql
              output: lib/data/graphql/query/payment_get_bank_list_query_graphql.dart
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/query/payment_get_payment_type_list_query.graphql
              output: lib/data/graphql/query/payment_get_payment_type_list_query_graphql.dart
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/query/refresh_token_query.graphql
              output: lib/data/graphql/query/refresh_token_query_graphql.dart

            #### Subscription ####
#            - schema: graphql_schema/schema.graphql
#              queries_glob: graphql_queries/subscription/demo_subscription.graphql
#              output: lib/data/graphql/subscription/demo_subscription_graphql.dart