targets:
  $default:
    sources:
      - lib/**
      - graphql_queries/**
      - graphql_schema/schema.graphql
    builders:
      artemis:
        options:
          generate_helpers: true
          scalar_mapping:
            - graphql_type: BigInteger
              dart_type: int
              use_custom_parser: true
          schema_mapping:

            ##### Mutation ####
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/mutation/create_category_mutation.graphql
              output: lib/data/graphql/mutation/create_category_mutation_graphql.dart
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/mutation/create_customer_mutation.graphql
              output: lib/data/graphql/mutation/create_customer_mutation_graphql.dart
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/mutation/create_emergency_mutation.graphql
              output: lib/data/graphql/mutation/create_emergency_mutation_graphql.dart
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/mutation/create_faq_mutation.graphql
              output: lib/data/graphql/mutation/create_faq_mutation_graphql.dart
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/mutation/create_payment_mutation.graphql
              output: lib/data/graphql/mutation/create_payment_mutation_graphql.dart
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/mutation/create_policy_mutation.graphql
              output: lib/data/graphql/mutation/create_policy_mutation_graphql.dart
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/mutation/create_product_list_mutation.graphql
              output: lib/data/graphql/mutation/create_product_list_mutation_graphql.dart
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/mutation/create_promotion_mutation.graphql
              output: lib/data/graphql/mutation/create_promotion_mutation_graphql.dart
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/mutation/create_recuse_car_order_mutation.graphql
              output: lib/data/graphql/mutation/create_recuse_car_order_mutation_graphql.dart
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/mutation/create_recuse_moto_order_mutation.graphql
              output: lib/data/graphql/mutation/create_recuse_moto_order_mutation_graphql.dart
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/mutation/create_repairing_order_mutation.graphql
              output: lib/data/graphql/mutation/create_repairing_order_mutation_graphql.dart
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/mutation/delete_repairing_order_mutation.graphql
              output: lib/data/graphql/mutation/delete_repairing_order_mutation_graphql.dart
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/mutation/login_mutation.graphql
              output: lib/data/graphql/mutation/login_mutation_graphql.dart
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/mutation/login_with_auth_mutation.graphql
              output: lib/data/graphql/mutation/login_with_auth_mutation_graphql.dart
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/mutation/motor_ins_create_order_mutation.graphql
              output: lib/data/graphql/mutation/motor_ins_create_order_mutation_graphql.dart
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/mutation/register_otp_mutation.graphql
              output: lib/data/graphql/mutation/register_otp_mutation_graphql.dart
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/mutation/update_password_mutation.graphql
              output: lib/data/graphql/mutation/update_password_mutation_graphql.dart
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/mutation/update_profile_mutation.graphql
              output: lib/data/graphql/mutation/update_profile_mutation_graphql.dart
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/mutation/update_repairing_order_mutation.graphql
              output: lib/data/graphql/mutation/update_repairing_order_mutation_graphql.dart
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/mutation/verify_otp_mutation.graphql
              output: lib/data/graphql/mutation/verify_otp_mutation_graphql.dart

            #### Query ####
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/query/app_notification_item_query.graphql
              output: lib/data/graphql/query/app_notification_item_query_graphql.dart
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/query/app_notification_list_query.graphql
              output: lib/data/graphql/query/app_notification_list_query_graphql.dart
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/query/feature_flag_clear_feature_cache_query.graphql
              output: lib/data/graphql/query/feature_flag_clear_feature_cache_query_graphql.dart
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/query/feature_flag_clear_version_cache_query.graphql
              output: lib/data/graphql/query/feature_flag_clear_version_cache_query_graphql.dart
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/query/feature_flag_get_user_version_query.graphql
              output: lib/data/graphql/query/feature_flag_get_user_version_query_graphql.dart
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/query/feature_flag_list_feature_query.graphql
              output: lib/data/graphql/query/feature_flag_list_feature_query_graphql.dart
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/query/get_bank_list_query.graphql
              output: lib/data/graphql/query/get_bank_list_query_graphql.dart
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/query/get_category_list_query.graphql
              output: lib/data/graphql/query/get_category_list_query_graphql.dart
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/query/get_customer_list_query.graphql
              output: lib/data/graphql/query/get_customer_list_query_graphql.dart
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/query/get_emergency_list_query.graphql
              output: lib/data/graphql/query/get_emergency_list_query_graphql.dart
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/query/get_faq_list_query.graphql
              output: lib/data/graphql/query/get_faq_list_query_graphql.dart
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/query/get_payment_type_list_query.graphql
              output: lib/data/graphql/query/get_payment_type_list_query_graphql.dart
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/query/get_policy_list_query.graphql
              output: lib/data/graphql/query/get_policy_list_query_graphql.dart
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/query/get_product_list_query.graphql
              output: lib/data/graphql/query/get_product_list_query_graphql.dart
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/query/get_promotion_list_query.graphql
              output: lib/data/graphql/query/get_promotion_list_query_graphql.dart
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/query/get_recuse_moto_brand_query.graphql
              output: lib/data/graphql/query/get_recuse_moto_brand_query_graphql.dart
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/query/get_recuse_moto_model_query.graphql
              output: lib/data/graphql/query/get_recuse_moto_model_query_graphql.dart
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/query/get_recuse_moto_product_query.graphql
              output: lib/data/graphql/query/get_recuse_moto_product_query_graphql.dart
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/query/motor_ins_get_metadata_query.graphql
              output: lib/data/graphql/query/motor_ins_get_metadata_query_graphql.dart
            - schema: graphql_schema/schema.graphql
              queries_glob: graphql_queries/query/refresh_token_query.graphql
              output: lib/data/graphql/query/refresh_token_query_graphql.dart

            #### Subscription ####
#            - schema: graphql_schema/schema.graphql
#              queries_glob: graphql_queries/subscription/demo_subscription.graphql
#              output: lib/data/graphql/subscription/demo_subscription_graphql.dart